on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.20.2"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - id: package
        run: |
          make tar
          for i in build/out/*.tar.gz; do
            echo ${i}
            tar -tvf ${i}
          done
          echo "version=$(make get-version)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: coredns
          path: build/out
          retention-days: ${{ github.event_name == 'pull_request' && 1 || 30 }}
      - id: existing-tags
        name: Get existing tags
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "tags=$(gh api repos/{owner}/{repo}/releases | jq -c 'map(.tag_name)')" >> $GITHUB_OUTPUT
      - name: Create release
        if: >-
          github.event_name == 'workflow_dispatch'
          || (github.event_name == 'push'
            && !contains(fromJSON(steps.existing-tags.outputs.tags), steps.package.outputs.version)
          )
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package.outputs.version }}
          files: |
            build/out/*
